### ISSUE TITLE
Version iOS

### ISSUE THREAD

**Issue by M-Rick** [jesuisundesdeux/vigilo-android#2]
Bonjour

Sur votre page vous indiquez ceci :

> Pourquoi Vigilo n’est pas disponible sur iOS ?
> Vigilo a été developpé sur iOS. Malgré celà, la politique de publication sur l’Apple Store ne permet pas sa publication.
> Des tentatives seront de nouveau effectuées.

Mais de quelles restrictions s'agit-il, je ne comprends pas?

Ce n'est ni un problème d'ouverture de code, ni que l'application soit libre puisqu'il y en a déjà plein. Quel est le type de la licence d'ailleurs, ce n'est indiqué nulle-part ?

https://en.wikipedia.org/wiki/List_of_free_and_open-source_iOS_applications

**Comment by vincentsaluzzo** [comment]
Hello @M-Rick. 

Je suis le développeur de l'application iOS. La restrictions concerne l'AppStore lui-même.
Apple ne nous a pas permis de mettre en ligne l'application Vigilo sur l'AppStore car elle enfreint des règles de celui-ci.

**Comment by badele** [comment]
Salut @M-Rick Je complète le commentaire de @vincentsaluzzo 

De ce que j'ai compris, d'après **Apple** Vigilo enfreindrait la vie privée (malgré la feature qui permet le floutage des plaques d’immatriculations, de plus dans la loi française, donner une plaque d’immatriculation n'est pas illégale , car seul la police peut avoir une adresse depuis une plaque
